before_script:
    - export VERSION=1.0.0
    - export MR_ID=1
    - export COMPILED_IMAGE=gcr.io/nib-backend-nonprod/python${VERSION}
    - export GITLAB_PROJECT_ID=24324549
    - export PRIVATE_TOKEN=jfsEHn6vC7CzVn_CNizR
  
stages:
  - build

build-web:
  stage: build
  environment:
    name: master
    url: https://ziro/api
  only:
    - master
  tags:
    - builder
  script:
    - git branch -f master HEAD
    - docker-compose build
    - docker push ${COMPILED_IMAGE}