# name of our workflow
name: Django CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' }} 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      
      - name: conect to cluster
        run: echo "test"

  build: # package job for building and publishing docker images
    needs: test
    runs-on: self-hosted
    env:
      VERSION: 10.0.0
      COMPILED_IMAGE: gcr.io/nib-backend-nonprod/python

    if: ${{ github.event_name == 'push' }} # will be fired if the trigger event is a push event.
    steps:
      - name: Checkout Code # checking out code.
        uses: actions/checkout@v2
      
      - name: Build Image
        run: docker-compose build

      - name: Push Image
        run: sudo docker push $COMPILED_IMAGE:$VERSION

  deploy:
    needs: [test, build]
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' }} 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      
      - name: conect to cluster
        run: echo "kubectl apply"


        
    